-- MySQL Script generated by MySQL Workbench
-- Wed Jul 26 18:00:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rh_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rh_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rh_schema` DEFAULT CHARACTER SET utf8 ;
USE `rh_schema` ;

-- -----------------------------------------------------
-- Table `rh_schema`.`T_RH_ADDRESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rh_schema`.`T_RH_ADDRESS` (
  `id_address` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `complement` VARCHAR(45) NULL,
  `zip_code` CHAR(8) NULL,
  `district` VARCHAR(45) NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_address`),
  UNIQUE INDEX `id_address_UNIQUE` (`id_address` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh_schema`.`T_RH_CLIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rh_schema`.`T_RH_CLIENT` (
  `cnpj` CHAR(14) NOT NULL,
  `company_name` VARCHAR(50) NOT NULL,
  `trading_name` VARCHAR(50) NULL,
  `inscr_estadual` CHAR(9) NULL,
  `phone` VARCHAR(14) NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `logo` BLOB NULL,
  `T_RH_ADDRESS_id_address` INT NOT NULL,
  PRIMARY KEY (`cnpj`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  INDEX `fk_T_RH_CLIENT_T_RH_ADDRESS1_idx` (`T_RH_ADDRESS_id_address` ASC) VISIBLE,
  CONSTRAINT `fk_T_RH_CLIENT_T_RH_ADDRESS1`
    FOREIGN KEY (`T_RH_ADDRESS_id_address`)
    REFERENCES `rh_schema`.`T_RH_ADDRESS` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh_schema`.`T_RH_WKIT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rh_schema`.`T_RH_WKIT` (
  `id_wkit` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `image` BLOB NOT NULL,
  `T_RH_CLIENT_cnpj` CHAR(14) NOT NULL,
  PRIMARY KEY (`id_wkit`),
  UNIQUE INDEX `id_wkit_UNIQUE` (`id_wkit` ASC) VISIBLE,
  INDEX `fk_T_RH_WKIT_T_RH_CLIENT1_idx` (`T_RH_CLIENT_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_T_RH_WKIT_T_RH_CLIENT1`
    FOREIGN KEY (`T_RH_CLIENT_cnpj`)
    REFERENCES `rh_schema`.`T_RH_CLIENT` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh_schema`.`T_RH_TRACKING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rh_schema`.`T_RH_TRACKING` (
  `id_tracking` INT NOT NULL AUTO_INCREMENT,
  `tracking_n` VARCHAR(45) NULL,
  `status` ENUM('A ENVIAR', 'ENVIADO', 'ENTREGUE') NOT NULL,
  `T_RH_WKIT_id_wkit` INT NOT NULL,
  PRIMARY KEY (`id_tracking`),
  UNIQUE INDEX `id_tracking_UNIQUE` (`id_tracking` ASC) VISIBLE,
  INDEX `fk_T_RH_TRACKING_T_RH_WKIT1_idx` (`T_RH_WKIT_id_wkit` ASC) VISIBLE,
  CONSTRAINT `fk_T_RH_TRACKING_T_RH_WKIT1`
    FOREIGN KEY (`T_RH_WKIT_id_wkit`)
    REFERENCES `rh_schema`.`T_RH_WKIT` (`id_wkit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh_schema`.`T_RH_EMPLOYEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rh_schema`.`T_RH_EMPLOYEE` (
  `cpf` CHAR(11) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `surname` VARCHAR(30) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(14) NOT NULL,
  `birth_date` DATE NOT NULL,
  `company_position` VARCHAR(20) NOT NULL,
  `access` ENUM('ADMIN', 'MANAGER', 'DEFAULT') NOT NULL,
  `T_RH_CLIENT_cnpj` CHAR(14) NOT NULL,
  `T_RH_ADDRESS_id_address` INT NOT NULL,
  `T_RH_TRACKING_id_tracking` INT NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `fk_T_RH_EMPLOYEE_T_RH_CLIENT_idx` (`T_RH_CLIENT_cnpj` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_T_RH_EMPLOYEE_T_RH_ADDRESS1_idx` (`T_RH_ADDRESS_id_address` ASC) VISIBLE,
  INDEX `fk_T_RH_EMPLOYEE_T_RH_TRACKING1_idx` (`T_RH_TRACKING_id_tracking` ASC) VISIBLE,
  CONSTRAINT `fk_T_RH_EMPLOYEE_T_RH_CLIENT`
    FOREIGN KEY (`T_RH_CLIENT_cnpj`)
    REFERENCES `rh_schema`.`T_RH_CLIENT` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_RH_EMPLOYEE_T_RH_ADDRESS1`
    FOREIGN KEY (`T_RH_ADDRESS_id_address`)
    REFERENCES `rh_schema`.`T_RH_ADDRESS` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_RH_EMPLOYEE_T_RH_TRACKING1`
    FOREIGN KEY (`T_RH_TRACKING_id_tracking`)
    REFERENCES `rh_schema`.`T_RH_TRACKING` (`id_tracking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh_schema`.`T_RH_WK_ITEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rh_schema`.`T_RH_WK_ITEM` (
  `id_wk_item` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `image` BLOB NOT NULL,
  `T_RH_WKIT_id_wkit` INT NOT NULL,
  PRIMARY KEY (`id_wk_item`),
  UNIQUE INDEX `id_wk_item_UNIQUE` (`id_wk_item` ASC) VISIBLE,
  INDEX `fk_T_RH_WK_ITEM_T_RH_WKIT1_idx` (`T_RH_WKIT_id_wkit` ASC) VISIBLE,
  CONSTRAINT `fk_T_RH_WK_ITEM_T_RH_WKIT1`
    FOREIGN KEY (`T_RH_WKIT_id_wkit`)
    REFERENCES `rh_schema`.`T_RH_WKIT` (`id_wkit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh_schema`.`T_RH_CHAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rh_schema`.`T_RH_CHAT` (
  `id_chat` INT NOT NULL AUTO_INCREMENT,
  `T_RH_CLIENT_cnpj` CHAR(14) NOT NULL,
  `T_RH_EMPLOYEE_cpf` CHAR(11) NOT NULL,
  PRIMARY KEY (`id_chat`),
  UNIQUE INDEX `id_chat_UNIQUE` (`id_chat` ASC) VISIBLE,
  INDEX `fk_T_RH_CHAT_T_RH_CLIENT1_idx` (`T_RH_CLIENT_cnpj` ASC) VISIBLE,
  INDEX `fk_T_RH_CHAT_T_RH_EMPLOYEE1_idx` (`T_RH_EMPLOYEE_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_T_RH_CHAT_T_RH_CLIENT1`
    FOREIGN KEY (`T_RH_CLIENT_cnpj`)
    REFERENCES `rh_schema`.`T_RH_CLIENT` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_RH_CHAT_T_RH_EMPLOYEE1`
    FOREIGN KEY (`T_RH_EMPLOYEE_cpf`)
    REFERENCES `rh_schema`.`T_RH_EMPLOYEE` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh_schema`.`T_RH_MESSAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rh_schema`.`T_RH_MESSAGE` (
  `id_message` INT NOT NULL AUTO_INCREMENT,
  `to` INT NOT NULL,
  `from` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `read_in` DATETIME NULL,
  `content` VARCHAR(500) NOT NULL,
  `T_RH_CHAT_id_chat` INT NOT NULL,
  PRIMARY KEY (`id_message`),
  UNIQUE INDEX `id_message_UNIQUE` (`id_message` ASC) VISIBLE,
  INDEX `fk_T_RH_MESSAGE_T_RH_CHAT1_idx` (`T_RH_CHAT_id_chat` ASC) VISIBLE,
  CONSTRAINT `fk_T_RH_MESSAGE_T_RH_CHAT1`
    FOREIGN KEY (`T_RH_CHAT_id_chat`)
    REFERENCES `rh_schema`.`T_RH_CHAT` (`id_chat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
